# Generated by Django 3.2.5 on 2022-10-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.TextField(default='', verbose_name='В ведите текст который получит пользователь при покупки'),
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
