# Generated by Django 3.2.5 on 2022-10-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_auto_20221024_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='В ведите текст который получит пользователь при покупки'),
        ),
    ]
