# Generated by Django 3.2.5 on 2022-10-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_order_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='text',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='В ведите текст который получит пользователь при покупки'),
        ),
    ]
