# Generated by Django 4.1.2 on 2022-10-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('configurations', models.TextField(verbose_name='Описание конфигурации')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('total', models.IntegerField(blank=True, verbose_name='Старая цена')),
                ('count', models.BooleanField(verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Услуги',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
