# Generated by Django 3.2.5 on 2022-11-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_country_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('configurations', models.TextField(verbose_name='Описание конфигурации')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('total', models.IntegerField(blank=True, verbose_name='Старая цена')),
                ('count', models.BooleanField(verbose_name='В наличии')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_product', to='shop.product')),
            ],
            options={
                'verbose_name': 'Товары',
                'verbose_name_plural': 'Товар',
            },
        ),
    ]
