# Generated by Django 3.2.5 on 2022-11-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_addproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Дополнительные услуги', 'verbose_name_plural': 'Дополнительная услуга'},
        ),
    ]
