# Generated by Django 3.2.5 on 2022-11-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addproduct',
            options={'verbose_name': 'Дополнительные услуги', 'verbose_name_plural': 'Дополнительная услуга'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товары', 'verbose_name_plural': 'Товар'},
        ),
    ]
