# Generated by Django 3.2.5 on 2022-11-01 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20221101_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='add_product',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.addproduct', verbose_name='Дополнительные услуги'),
        ),
    ]
