# Generated by Django 3.2.5 on 2022-11-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221101_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproduct',
            name='product',
        ),
        migrations.CreateModel(
            name='AddItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_products', to='shop.addproduct')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_products', to='shop.product')),
            ],
        ),
    ]
