# Generated by Django 3.2.5 on 2022-11-02 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20221102_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='add_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_items', to='shop.addproduct'),
        ),
    ]
